project:
  type: book

book:
  title: "THESIS"
  author: "Florian Ricour"
  date: "19/10/2022"
  chapters:
    - index.qmd
    #- summary.qmd
    #- intro.qmd
    #- observingCarbonCycle.qmd
    #- uvp6_part.qmd
    - article3.qmd
    #- discussion.qmd
    - references.qmd
    - annexes.qmd

bibliography: references.bib
csl: journal-of-oceanography.csl
#bibliography: https://api.citedrive.com/bib/fc082fe7-66b6-4ce0-971e-df5eb80d7808/references.bib?x=eyJpZCI6ICJmYzA4MmZlNy02NmI2LTRjZTAtOTcxZS1kZjVlYjgwZDc4MDgiLCAidXNlciI6ICIyNjg2IiwgInNpZ25hdHVyZSI6ICJhN2E2MmEyNTFmYjExZmI4MTA3OTUwOTQ0NjNiOTNiNjljNGNiOTVjODAyOWVhZDJiZmM2MDdkYzZkYjUwYjliIn0=/bibliography.bib
link-citations: true

format:
  #docx: default
  # html:
  #   theme: cosmo
  pdf:
    #pdf-engine: xelatex
    documentclass: scrreprt
    #cite-method: biblatex
    include-in-header: preamble.tex

editor: visual

execute: 
  echo: false
  warning: false
  error: true
  cache: true