project:
  type: book

book:
  title: ""
  subtitle: ""
  genre: ""
  date: ""
  author: ""
  chapters:
    - index.qmd
    #- merci.qmd
    #- scientific_activities.qmd
    #- summary.qmd
    #- intro.qmd
    - observingCarbonCycle.qmd
    - uvp6_part.qmd
    - article3.qmd
    - bcp_sequestration.qmd
    - discussion.qmd
    - references.qmd
  #appendices: 
    #- annexes.qmd
    
bibliography: references.bib
csl: journal-of-oceanography.csl
link-citations: true


format:
  #docx: default
  # html:
  #   theme: cosmo
  pdf:
    #pdf-engine: xelatex
    documentclass: scrreprt
    #cite-method: biblatex
    include-in-header: preamble.tex
    #template-partials: 
    #  - before-body.tex
    lof: true
    lot: true

editor: visual

execute: 
  echo: false
  warning: false
  error: true
  cache: true