project:
  type: book

book:
  title: "THESIS"
  author: "Florian Ricour"
  date: "19/10/2022"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - observingCarbonCycle.qmd
    - article3.qmd
    - references.qmd

bibliography: references.bib

format:
  #docx: default
  html:
    theme: cosmo
  # pdf:
  #   #pdf-engine: xelatex
  #   documentclass: scrreprt

editor: visual

execute: 
  echo: false
  warning: false
  error: true
  cache: true