# Acknowledgments

Thanks to the members of the jury for taking the time to read and evaluate this three and a half year work. I am looking forward to debate it during the defense.

Cette thèse a été particulière à bien des égards, avec son lot de positifs et de négatifs mais surtout avec son lot de rebondissements qui m'ont permis d'affûter mes connaissances, ma résilience et je l'espère ma tolérance. Pour cela, je tiens à remercier chaleureusement toutes les personnes y ayant contribué de près ou de loin.

Merci à Hervé, Lionel et Jean-Olivier pour leur accueil au Laboratoire de Villefranche-sur-Mer et pour leur disponibilité ainsi que pour leurs conseils avisés, tant scientifiques que personnels.

Merci à Alex, Charles et Arthur pour leur aide et leur gentillesse.

Merci également aux personnes que j'ai pu cotoyer à COMPLEX comme chez OMTAB depuis mon passage en stage en 2018 et les multiples allers-retours Belgique-France.

Merci à Antoine Mangin de m'avoir prêté un bureau dans les locaux d'ACRI sur Grasse l'été dernier pendant que mon appartement servait d'Airbnb estival pour le plus grand bonheur du portefeuille de mon proprio.

Un grand merci à mes colocs de bureau: Ophélie, Laetitia et Thelma pour votre soutien et votre bonne humeur sans faille (contrairement à moi).

Merci à AMP (elle se reconnaitra), Chloé et Anaïs pour les pauses midi sur le ponton. AMP, merci d'avoir accepté de vivre virtuellement avec moi afin que la sécu daigne enfin me donner une carte vitale !

Ne me demandez pas des noms de restos ou de bars sur la côte d'Azur, je n'en ai aucune idée. Par contre, je connais pas mal les routes du coin. Merci à tous ceux qui ont partagé (ou subi) des kilomètres avec moi, surtout en montée (le plat pays, qui est le mien): Flavien, Ophé, Lucas, Thelma, Laeti et Satoshi.

Un grand merci à Marine et Alice pour leur bienveillance. Marine, je te souhaite le meilleur pour tes projets futurs mais fais attention à qui tu donnes tes clés quand même.

Merci également à Alex qui a été un excellent roommate pendant les confinements, couvre-feux et ordonnances en tout genre. See you in London !

Merci aux Liégeois(es) (Thomas, Florent, Flop, Nico, Evgeny et Lucie) et en particulier Hadrien qui a accepté de m'avoir comme coloc pendant plusieurs mois (et qui y a survécu).

Merci aux Montois (Mathieu, Chris, Flo, Ju & Ju) pour votre soutien à distance, un mariage en 3 actes et pour vos visites sur Nice. Petite dédicace à Ju K qui, à force d'avoir joué avec le diable en subissant l'enfer des pourcentages, va littéralement en devenir un. Vivement 2024 pour casser la baraque.

Un très grand merci à ma famille nucléaire qui ne comprend toujours pas mon job mais qui fait semblant quand je lui explique, c'est le principal. C'est vrai que la défense tombe mal au niveau timing donc on se voit à la Ducasse :-)

Enfin, un grand merci à une personne toute particulière qui en a probablement marre que je parle de la Belgique mais qui à présent est parfaite bilingue, mission accomplie?
