# Summary {.unnumbered}

**Towards a new insight of the carbon transport in the global ocean**

The ocean is known to play a key role in the carbon cycle. Without it, atmospheric CO2 levels would be much higher than what they are today thanks to the presence of carbon pumps that maintain a gradient of dissolved inorganic carbon (DIC) between the surface and the deep ocean. The biological carbon pump (BCP) is primarily responsible for this gradient. It consists in a series of ocean processes through which inorganic carbon is fixed as organic matter by photosynthesis in sunlit surface waters and then transported to the ocean interior and possibly the sediment where it will be sequestered from the atmosphere for millions of years. The BCP was long thought as solely the gravitational settling of particulate organic carbon (POC). However, a new paradigm for the BCP has recently been defined in which physically and biologically mediated particle injection pumps have been added to the original definition. Physically mediated particle injection pumps provide a pathway to better understand the transport of dissolved organic carbon (DOC) whereas biologically mediated particle injection pumps focus on the transport of POC by vertically migrating animals, either daily or seasonally. Therefore, a better understanding of these processes could help bridge the gap between carbon leaving the surface and carbon demand in the ocean interior. To address this new paradigm, this work will benefit from the advent of recent sensors that equip a new generation of Biogeochemical-Argo floats (BGC-Argo). The first part focuses on the development of an embedded zooplankton classification model for the Underwater Vision Profiler 6 (UVP6) under strict technical and energy constraints. The second part studies particle and carbon fluxes in the Labrador Sea using BGC-Argo floats equipped for the first time with the UVP6 and an optical sediment trap (OST), providing two independent measurements of sinking particles. The last part consists in revisiting the BCP using a new framework called CONVERSE for Continuous Vertical Sequestration. With this new approach, we re-evaluate the total carbon sequestered from the atmosphere (> 100 years) by the BCP and its transport pathways on the entire water column, in contrast to the carbon sequestration typically assumed below a fixed reference depth.

**Keywords** Carbon pumps -- Underwater Vision Profiler 6 -- BGC-Argo floats -- Machine learning

```{=latex}
\newpage
```

**Vers une meilleur compréhension du transport du carbone dans l'océan global**

L'océan est connu pour jouer un rôle clé dans le cycle du carbone. Sans lui, les niveaux de CO2 atmosphérique seraient bien plus élevés qu'aujourd'hui grâce à la présence de pompes à carbone qui maintiennent un gradient de carbone inorganique dissous (DIC) entre la surface et le fond de l'océan. La pompe à carbone biologique (BCP) est principalement responsable de ce gradient. Elle consiste en une série de processus océaniques au cours desquels le carbone inorganique est converti en matière organique via la photosynthèse dans les eaux de surface, puis transporté vers l'intérieur de l'océan et éventuellement les sédiments où il sera séquestré par rapport à l'atmosphère pour des millions d'années. La BCP était longtemps considérée comme étant uniquement la déposition gravitationnelle de carbone organique particulaire (POC). Cependant, un nouveau paradigme pour la BCP a récemment été défini dans lequel des pompes d'origine physique et biologique d'injection de particules ont été ajoutées à la définition originale. Les pompes physiques d'injection de particules fournissent un moyen de mieux comprendre le transport de carbone organique dissous (DOC), tandis que les pompes biologique d'injection de particules se concentrent sur le transport de POC par des animaux migrant verticalement, quotidiennement ou saisonnièrement. Par conséquent, une meilleure compréhension de ces processus pourrait aider à combler l'écart entre le carbone quittant la surface et la demande de carbone dans l'océan profond. Pour aborder ce nouveau paradigme, ce travail bénéficiera de l'arrivée de capteurs récents équipant une nouvelle génération de flotteurs Biogéochimiques-Argo (BGC-Argo). La première partie se concentre sur le développement d'un modèle embarqué de classification de zooplancton pour l'Underwater Vision Profiler 6 (UVP6) avec des contraintes techniques et énergétiques strictes. La deuxième partie étudie les flux de particules et de carbone dans la mer du Labrador en utilisant des flotteurs BGC-Argo équipés pour la première fois de l'UVP6 et d'un piège à sédiments optique (OST), fournissant deux mesures indépendantes des particules. La dernière partie consiste à revisiter la BCP en utilisant un nouveau cadre appelé CONVERSE qui fait référence à la séquestration verticale continue du carbone dans la colonne d'eau. Avec cette nouvelle approche, nous réévaluons le carbone total séquestré par rapport à l'atmosphère (\> 100 ans) par la BCP et ses voies de transport sur toute la colonne d'eau, par opposition à la séquestration de carbone généralement supposée en-dessous d'une profondeur de référence fixe.

**Mots clés** Pompes à carbone -- Underwater Vision Profiler 6 -- Flotteurs BGC-Argo -- Machine learning